spring:
  profiles:
    active:
    - dev
---
spring:
  proiles: dev
  application:
    name: microservicecloud-config-atguigu-dev
---    
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test

 
 
